-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE GENDER = 'W'and TLNO is not null and extract(MONTH from DATE_OF_BIRTH) = 3
order by MEMBER_ID asc;